name: Template
on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'spring-boot-webflux-example'
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Prepare
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          export LC_CTYPE=C
          export LANG=C

          NAME="${GITHUB_REPOSITORY##*/}"
          ACTOR=$(echo "${GITHUB_ACTOR}" | tr '[:upper:]' '[:lower:]')
          SAFE_NAME=$(echo "${NAME}" | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_ACTOR=$(echo "${ACTOR}" | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.github.${SAFE_ACTOR}.${SAFE_NAME}"

          echo "Using GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "Using GITHUB_ACTOR=${GITHUB_ACTOR}"
          echo "Using NAME=${NAME}"
          echo "Using GROUP=${GROUP}"

          sed -i "s/%NAME%/${NAME}/g" .github/template-files/*
          sed -i "s/%REPOSITORY%/${GITHUB_REPOSITORY/\//\\/}/g" .github/template-files/*
          sed -i "s/%GROUP%/${GROUP}/g" .github/template-files/*

          find src -type f -exec sed -i "s/spring.boot.webflux.template/${GROUP}/g" {} +

          find deployment -type f -exec sed -i "s/spring-boot-webflux-example/${NAME}/g" {} +
          find deployment -type f -exec sed -i "s/spring.boot.webflux.template/${GROUP}/g" {} +
          find deployment -type f -exec sed -i "s/jecklgamis/${ACTOR}/g" {} +

          find . -name "*.sh" -type f -exec sed -i "s/spring-boot-webflux-example/${NAME}/g" {} +
          find . -name "*.sh" -type f -exec sed -i "s/spring.boot.webflux.template/${GROUP}/g" {} +
          find . -name "*.sh" -type f -exec sed -i "s/jecklgamis/${ACTOR}/g" {} +

          find . -name Makefile -type f -exec sed -i "s/spring-boot-webflux-example/${NAME}/g" {} +
          find . -name Makefile -type f -exec sed -i "s/spring.boot.webflux.template/${GROUP}/g" {} +
          find . -name Makefile -type f -exec sed -i "s/jecklgamis/${ACTOR}/g" {} +

          find . -name pom.xml -type f -exec sed -i "s/spring-boot-webflux-example/${NAME}/g" {} +
          find . -name pom.xml -type f -exec sed -i "s/spring.boot.webflux.template/${GROUP}/g" {} +
          find . -name pom.xml -type f -exec sed -i "s/com.jecklgamis/${GROUP}/g" {} +

          find . -name Dockerfile -type f -exec sed -i "s/spring-boot-webflux-example/${NAME}/g" {} +
          find . -name Dockerfile -type f -exec sed -i "s/Jerrico Gamis/FirstName LastName/g" {} +
          find . -name Dockerfile -type f -exec sed -i "s/jecklgamis@gmail.com/user@some-domain/g" {} +

          mkdir -p src/main/java/${GROUP//.//}
          mkdir -p src/test/java/${GROUP//.//}
          cp -R .github/template-files/* .
          cp -R src/main/java/spring/boot/webflux/template/* src/main/java/${GROUP//.//}/
          cp -R src/test/java/spring/boot/webflux/template/* src/test/java/${GROUP//.//}/

          rm -rf \
            .circleci \
            .github/readme \
            .github/template-files \
            .github/workflows/template.yml \
            .idea/icon.png \
            src/main/java/spring \
            src/test/java/spring \
            LICENSE

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Prepare repo" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}